"""add groq api key

Revision ID: 1319fd1fe241
Revises: bdb28fdb7326
Create Date: 2026-06-18 11:02:27.445393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1319fd1fe241'
down_revision: Union[str, Sequence[str], None] = 'bdb28fdb7326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('groq_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'groq_api_key')
    # ### end Alembic commands ###
